name: VirtEngine Documentation
version: 1.5.1
url: https://docs.virtengine.com
timezone:    Australia/Sydney	
locale:      en_US
future:      true
highlighter: rouge
markdown:    kramdown

author:
  name: VirtEngine
  email: hello@virtengine.com

# Owner/author information
owner:
  name:           VirtEngine by DET.io
  site:           https://det.io
  avatar:         images/avatar-cloud.png
  bio:            "VirtEngine specializes in building Virtualization Software and powering Cloud Service Providers / Hosting Providers.."
  email:          jonathan@det.io
  # Twitter nick for use in Twitter cards and follow button.
  twitter: VirtEngine # if no twitter in this config, the twitter follow button will be removed
  # GitHub nick for use in follow button in author block.
  github: VirtEngine

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: "github"
    url: "https://github.com/VirtEngine"
  - title: "linkedin"
    url: "https://www.linkedin.com/company/7589532"
  - title: "youtube"
    url: "https://www.youtube.com/channel/UCT68VXnWJU17fgdOy1TQFaA"

builds:
  - virtengine
  - VirtEngine

plans:
  - free
  - enterprise

menu:
  - title: 'Home'
    url: 'https://virtengine.com'
  - title: 'Fork'
    url: 'https://github.com/DET-io/VirtEngine'
  - title: 'Documentation'
    url: 'https://docs.virtengine.com'
  - title: 'Forums'
    url: 'http://forums.virtengine.com'
  - title: 'Blog'
    url: 'http://blog.virtengine.com'

collections:
  overview:
    title: Overview
    permalink: /overview/:title/
    active_prefix: overview
    output: true
    order: 1
  gettingstarted:
    title: Getting Started
    permalink: /gettingstarted/:title/
    active_prefix: gettingstarted
    output: true
    order: 2
  installation:
    title: Installation
    permalink: /installation/:title/
    active_prefix: installation
    output: true
    order: 3
  configuration:
    title: Configuration
    permalink: /configuration/:title/
    active_prefix: configuration
    output: true
    order: 4
  machines:
    title: Machines
    permal`ink: /machines/:title/
    active_prefix: machines
    output: true
    order: 5
  prepackagedapps:
    title: Prepackaged Apps
    permalink: /prepackagedapps/:title/
    active_prefix: prepackagedapps
    output: true
    order: 6
  customapps:
    title: Custom Apps
    permalink: /customapps/:title/
    active_prefix: customapps
    output: true
    order: 7
  containers:
    title: Containers
    permalink: /containers/:title/
    active_prefix: containers
    output: true
    order: 8
  domains:
    title: Domains
    permalink: /domains/:title/
    active_prefix: domains
    output: true
    order: 9

defaults:
- scope:
    path: ""
  values:
    layout: docs
